name: Auto Commit

on:
  push:
    branches:
      - main

  schedule:
    - cron: '0 4 * * *'  # 4 AM UTC
    - cron: '0 12 * * *' # 12 PM UTC
    - cron: '0 15 * * *' # 3 PM UTC
    - cron: '0 18 * * *' # 6 PM UTC
    - cron: '0 19 * * *' # 7 PM UTC

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Modify Last Update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED

      - name: Commit Changes
        run: |
          git config --local user.name "Asep haryana"
          git config --local user.email "exceednethunter@gmail.com"
          git add -A

          arr[0]="chore(bot): 🔥 auto commit"
          arr[1]="chore(bot): 💀 auto commit"
          arr[2]="chore(bot): 👹 auto commit"
          arr[3]="chore(bot): 👺 auto commit"
          arr[4]="chore(bot): 🤡 auto commit"
          arr[5]="chore(bot): 👻 auto commit"
          arr[6]="chore(bot): 👽 auto commit"
          arr[7]="chore(bot): 🤖 auto commit"
          arr[8]="chore(bot): 👾 auto commit"
          arr[9]="chore(bot): 😈 auto commit"

          rand=$[$RANDOM % ${#arr[@]}]

          git commit -m "${arr[$rand]}"

      - name: GitHub Push
        uses: ad-m/github-push-action@master
        with:
          force: true
          directory: '.'
          github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
